CREATE USER IF NOT EXISTS evd_analytics WITH PASSWORD '@MIcrosoft2010';
CREATE DATABASE IF NOT EXISTS evd_app;
GRANT ALL PRIVILEGES ON DATABASE evd_app TO warehouse;
GRANT ALL PRIVILEGES ON DATABASE evd_raw TO warehouse;
