export const POSTGRES_DATA_POOL = 'POSTGRES_DATA_POOL';
export const POSTGRES_APP_POOL = 'POSTGRES_APP_POOL';
export const POSTGRES_DATA_SERVICE = 'POSTGRES_DATA_SERVICE';
export const POSTGRES_APP_SERVICE = 'POSTGRES_APP_SERVICE';
